apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: terraria-tcp
  namespace: terraria
spec:
  entryPoints:
    - terraria
  routes:
    - match: HostSNI(`*`)
      services:
        - name: terraria-service
          port: 7777