apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-terraria
  namespace: terraria
  labels:
    type: local
spec:
  storageClassName: storage-terraria
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv-terraria"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-terraria
  namespace: terraria
spec:
  storageClassName: storage-terraria
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi